[[main]]
  identifier = "docs"
  name = "文档"
  url = "docs"
  weight = 1

[[main]]
  identifier = "tips"
  name = "要点"
  url = "tips"
  weight = 2

[[main]]
  identifier = "blog"
  name = "博客"
  url = "blog"
  weight = 3
